name: Build Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  PROJECT: mail_sync

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build Binary
        run: |
          cargo build --all --release
          strip target/release/${{ env.PROJECT }}
          mv target/release/${{ env.PROJECT }} target/release/${{ env.PROJECT }}_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ env.PROJECT }}_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
